### ISSUE TITLE
Pipe to stdout?

### ISSUE THREAD

**Issue by ghost** [WHO53/wvkbd-phosh-osk#3]
Hi again! Do you happen to know if it's possible to output to stdout, for use with something like clickclack (audible/haptic feedback) or swipeguess (prediction/swipe input)? Normally, running wvkbd with the `-O` option outputs a character to stdout, so it can be piped to another program for further processing. I did try to add the option w/ a pipe to the puri.sm.OSK0.desktop file, and while Phosh started without error, the keyboard no longer displayed at all.

**Comment by ghost** [comment]
So I do have a hacky solution to this. Basically just `ps aux | grep wvkbd` to get the ID of the process, then I run another instance with my string of pipes afterward: `wvkbd -O | swipeGuess wordlist.txt | completelyTypeWord.sh &` then kill the previous instance (`sudo kill [####]`). I can probably even toss this in a shell script to autorun after the first instance starts, and while that may very well work, it feels... gross. Won't stop me either way, but if there is a more elegant solution, I'll take it lol

EDIT: Or could I just replace `wvkbd` in the desktop file with a shell script that launches it using the piped command above? I suppose I could 🤔

**Comment by who53** [comment]
Maybe try /bin/sh -c "command" in .desktop

**Comment by ghost** [comment]
> Maybe try /bin/sh -c "command" in .desktop

That'd probably do it. So far I've just been experimenting with gesture typing, and trying different length/sorting for my wordlist, so manually starting from the terminal has been fine, but I think I've landed on something usable that I'll want to test more extensively.

Regardless, this doesn't really have anything to do with your code. StackOverflow probably would have been a better venue for this, lol.
